"""Subprocess-git writer (BL-30 commit 5).

Materialises the renderer's ``{path: content}`` tree to disk
under ``{repos_dir}/{project_id}/`` and commits with a
semantic message. Tags the commit when the Article-1 § 8
exit threshold is met for the first time at the current
cycle count.

External tool gating: ``git`` is opt-in (``enable_git: true``
in ``backend/config/plugins/learning-repo.yaml``). When the
binary is missing on PATH, this module raises
``ExternalServiceError("git", ...)`` which the global handler
maps to HTTP 502 — matches the Pandoc / TTS pattern from
``code-hygiene.md``.
"""

from __future__ import annotations

import logging
import os
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

from .thresholds import latest_exit_threshold_cycle

if TYPE_CHECKING:
    from .context import RenderContext

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class PersistResult:
    """Return shape of :func:`persist_to_disk_and_commit`."""

    repo_path: Path
    files_written: int
    commit_sha: str
    tag: str | None  # ``"cycle-N-mastered"`` or ``None`` when threshold not met


def _ensure_git_on_path() -> None:
    if shutil.which("git") is None:
        from app.exceptions import ExternalServiceError

        raise ExternalServiceError(
            "git", "git binary not found on PATH. Install git or disable enable_git."
        )


def _run_git(repo: Path, *args: str) -> str:
    """Run ``git <args>`` in ``repo`` and return stdout.

    ``LC_ALL=C`` is forced so error-message substring checks
    (e.g. "nothing to commit") work regardless of the dev
    machine's locale — without this, German-locale envs report
    "nichts zu committen" and our match fails.
    """

    env = {**os.environ, "LC_ALL": "C", "LANG": "C"}
    completed = subprocess.run(
        ["git", *args],
        cwd=str(repo),
        check=True,
        capture_output=True,
        text=True,
        env=env,
    )
    return completed.stdout.strip()


def _init_repo_if_needed(repo: Path) -> None:
    """``git init`` (idempotent). Sets the default branch +
    a deterministic local user.email/name so commits never
    fail under an unconfigured CI / fresh dev VM."""

    if (repo / ".git").is_dir():
        return
    repo.mkdir(parents=True, exist_ok=True)
    _run_git(repo, "init", "--initial-branch=main")
    # Local-scope identity — doesn't touch the user's global
    # git config. Keeps the plugin self-contained.
    _run_git(repo, "config", "user.email", "adaptive-learner@localhost")
    _run_git(repo, "config", "user.name", "Adaptive Learner")
    logger.info("Initialised learning-repo git repository at %s", repo)


def _write_tree(repo: Path, tree: dict[str, str]) -> int:
    """Write each ``path → content`` entry to disk. Returns the
    file count. Sub-directories are created as needed."""

    for rel_path, content in tree.items():
        target = repo / rel_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
    return len(tree)


def _build_commit_message(ctx: RenderContext) -> str:
    """Subject + body matching the Article-3 spec.

    Subject form: ``Cycle N — V X/10, T Y/10`` where N is the
    cumulative session count at this commit and X/Y are the
    *latest* session's understanding + method_fit (each scaled
    to /10). When no rating exists yet, the subject still
    reports the cycle but omits the rating clause.
    """

    cycle_n = len(ctx.sessions)
    sessions_sorted = sorted(ctx.sessions, key=lambda s: s.started_at)
    latest_session = sessions_sorted[-1] if sessions_sorted else None
    rating = ctx.latest_rating(latest_session.id) if latest_session is not None else None

    if rating is not None:
        subject = f"Cycle {cycle_n} - U {rating.understanding * 2}/10, T {rating.method_fit * 2}/10"
    elif cycle_n > 0:
        subject = f"Cycle {cycle_n} - no rating yet"
    else:
        subject = "Initial render - no sessions yet"

    body_lines = [
        "",
        f"project: {ctx.project.topic}",
        f"sessions: {cycle_n}",
        f"topics: {len(ctx.topics)}",
        "",
        "Generated by adaptive-learner learning-repo plugin.",
    ]
    return subject + "\n" + "\n".join(body_lines)


def _commit_and_maybe_tag(repo: Path, ctx: RenderContext) -> tuple[str, str | None]:
    """Stage everything, commit, and tag if the exit threshold
    just became achievable. Returns (commit_sha, tag_name|None).

    When ``git commit`` reports "nothing to commit", we resolve
    to the current HEAD SHA (so callers always get a SHA back)
    and skip tagging — re-rendering an unchanged tree should be
    a no-op, not an error.
    """

    _run_git(repo, "add", ".")
    message = _build_commit_message(ctx)
    try:
        # ``-c commit.gpgsign=false`` keeps these machine-generated
        # artifact commits self-contained: a global ``commit.gpgsign=true``
        # (common on signing-enabled dev VMs / CI) would otherwise route the
        # commit through the user's GPG/SSH signer and fail with exit 128
        # ("failed to write commit object") for an automated, unattended
        # commit. Same intent as the deterministic local identity above —
        # the plugin's commits never depend on ambient git config.
        _run_git(repo, "-c", "commit.gpgsign=false", "commit", "-m", message)
    except subprocess.CalledProcessError as exc:
        if "nothing to commit" not in (exc.stdout or "") + (exc.stderr or ""):
            raise
        # Tree unchanged — fall through to read HEAD.
        logger.info("Nothing to commit at %s; tree unchanged from previous render.", repo)
    commit_sha = _run_git(repo, "rev-parse", "HEAD")
    tag_name = _maybe_tag(repo, ctx)
    return commit_sha, tag_name


def _maybe_tag(repo: Path, ctx: RenderContext) -> str | None:
    """Add a ``cycle-N-mastered`` tag if cycle N just achieved the
    exit threshold AND the tag doesn't already exist. The tag
    is idempotent across re-renders at the same cycle count."""

    cycle = latest_exit_threshold_cycle(ctx)
    if cycle is None:
        return None
    tag_name = f"cycle-{cycle}-mastered"
    existing_tags = _run_git(repo, "tag", "--list", tag_name)
    if existing_tags:
        # Already tagged a previous render at this cycle — leave
        # the historical tag pointing at the original commit.
        return None
    _run_git(repo, "tag", tag_name)
    logger.info("Tagged learning-repo at %s as %s", repo, tag_name)
    return tag_name


def persist_to_disk_and_commit(
    tree: dict[str, str],
    repos_dir: Path,
    project_id: str,
    ctx: RenderContext,
) -> PersistResult:
    """Top-level entry. Writes, commits, optionally tags."""

    _ensure_git_on_path()
    repo = repos_dir.expanduser() / project_id
    _init_repo_if_needed(repo)
    files_written = _write_tree(repo, tree)
    commit_sha, tag = _commit_and_maybe_tag(repo, ctx)
    return PersistResult(
        repo_path=repo,
        files_written=files_written,
        commit_sha=commit_sha,
        tag=tag,
    )
