# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for the Adaptive Learner launcher (Windows, Linux, macOS).
#
# Build:  poetry run pyinstaller adaptive-learner-launcher.spec
# Output:
#   Windows: dist/adaptive-learner-launcher.exe (single-file, windowed, icon embedded)
#   Linux:   dist/adaptive-learner-launcher (ELF binary)
#   macOS:   dist/AdaptiveLearner Launcher.app (bundle, icon if adaptive-learner.icns exists)
#
# The launcher implementation now lives in the docker-app-launcher PyPI
# package (#1064); this app is a thin ``__main__`` wrapper plus a
# ``launcher.json`` config. The launcher version is the static
# ``adaptive_learner_launcher.__version__`` literal (kept current by
# ``make sync-versions``), so no build-time version injection is needed here.
# Windows file metadata still comes from version_info.txt; the macOS bundle
# version below is updated by sync-versions.

import os
import sys

# Available at build time (docker-app-launcher is a project dependency). Lists
# every docker_app_launcher submodule the launcher imports lazily, so the
# frozen binary bundles them.
from docker_app_launcher.pyinstaller import hidden_imports
from PyInstaller.utils.hooks import collect_data_files

from adaptive_learner_launcher import bundle_manifest

block_cipher = None


a = Analysis(
    ["adaptive_learner_launcher/__main__.py"],
    pathex=[],
    binaries=[],
    datas=[
        # ONE source of truth (#2054): every wrapper-owned asset comes from
        # bundle_manifest.BUNDLE_ASSETS, which the wrapper's start-up
        # self-check and --verify-bundle assert against at runtime - the
        # spec cannot bundle something the check does not know, and vice
        # versa. docker-compose.prod.yml is deliberately NOT here: its
        # build contexts need the whole source tree, which the wrapper
        # provisions at runtime instead (_bootstrap_app_source).
        *bundle_manifest.spec_datas(),
        # The package's data files - the 11 i18n catalogs above all
        # (upstream #34 class); their presence is pinned via
        # bundle_manifest.BUNDLE_DIRS.
        *collect_data_files("docker_app_launcher"),
    ],
    hiddenimports=hidden_imports(),
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Keep the bundle lean: drop anything we definitely do not import.
        "numpy",
        "pandas",
        "matplotlib",
        "scipy",
        # Optional tray extra, deliberately NOT bundled: it costs megabytes
        # every learner downloads, and on GNOME a docked icon would need a
        # shell extension on top, so the promise would be conditional. The
        # dependency declaration was removed to match (pyproject.toml) - one
        # statement, not two that contradict each other. Complete, not just
        # intended, since docker-app-launcher 0.25.2: with no tray the X
        # CLOSES the launcher instead of minimizing it forever (#108). The
        # tray remains available to source installs via the `tray` extra.
        "PIL",
        "pystray",
    ],
    noarchive=False,
    cipher=block_cipher,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="adaptive-learner-launcher",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # Windows-only: embed icon + version metadata. On non-Windows builds
    # (used only for local smoke by Linux devs), these kwargs are ignored.
    icon=["adaptive-learner.ico"] if sys.platform == "win32" else None,
    version="version_info.txt" if sys.platform == "win32" else None,
)


# macOS .app bundle. Skipped on Windows and Linux.
# The icon file "adaptive-learner.icns" is generated by the macOS CI workflow
# (iconutil is macOS-only) before PyInstaller runs. If the file is
# missing, the bundle builds without a custom icon and falls back to
# PyInstaller's default.
if sys.platform == "darwin":
    app = BUNDLE(
        exe,
        name="AdaptiveLearner Launcher.app",
        icon="adaptive-learner.icns" if os.path.exists("adaptive-learner.icns") else None,
        bundle_identifier="com.adaptive_learner.launcher",
        info_plist={
            "CFBundleName": "AdaptiveLearner Launcher",
            "CFBundleDisplayName": "AdaptiveLearner Launcher",
            "CFBundleVersion": "2.12.0",
            "CFBundleShortVersionString": "2.12.0",
            "NSHighResolutionCapable": True,
            "NSRequiresAquaSystemAppearance": False,
        },
    )
