# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for the Adaptive Learner launcher (Windows, Linux, macOS).
#
# Build:  poetry run pyinstaller adaptive-learner-launcher.spec
# Output:
#   Windows: dist/adaptive-learner-launcher.exe (single-file, windowed, icon embedded)
#   Linux:   dist/adaptive-learner-launcher (ELF binary)
#   macOS:   dist/AdaptiveLearner Launcher.app (bundle, icon if adaptive-learner.icns exists)
#
# The launcher implementation now lives in the docker-app-launcher PyPI
# package (#1064); this app is a thin ``__main__`` wrapper plus a
# ``launcher.json`` config. The launcher version is the static
# ``adaptive_learner_launcher.__version__`` literal (kept current by
# ``make sync-versions``), so no build-time version injection is needed here.
# Windows file metadata still comes from version_info.txt; the macOS bundle
# version below is updated by sync-versions.

import os
import sys

# Available at build time (docker-app-launcher is a project dependency). Lists
# every docker_app_launcher submodule the launcher imports lazily, so the
# frozen binary bundles them.
from docker_app_launcher.pyinstaller import hidden_imports

block_cipher = None


a = Analysis(
    ["adaptive_learner_launcher/__main__.py"],
    pathex=[],
    binaries=[],
    datas=[
        # The launcher config: __main__ resolves ``../launcher.json`` relative
        # to the package dir, which is the bundle root (_MEIPASS) when frozen.
        ("launcher.json", "."),
        # Window icon (resolved best-effort at runtime; never fatal if absent).
        ("adaptive-learner.png", "."),
    ],
    hiddenimports=hidden_imports(),
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Keep the bundle lean: drop anything we definitely do not import.
        "numpy",
        "pandas",
        "matplotlib",
        "scipy",
        # Optional tray extra. tray.py is import-safe without it, so the frozen
        # binary simply runs without a system tray (tray works from source).
        "PIL",
        "pystray",
    ],
    noarchive=False,
    cipher=block_cipher,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="adaptive-learner-launcher",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # Windows-only: embed icon + version metadata. On non-Windows builds
    # (used only for local smoke by Linux devs), these kwargs are ignored.
    icon=["adaptive-learner.ico"] if sys.platform == "win32" else None,
    version="version_info.txt" if sys.platform == "win32" else None,
)


# macOS .app bundle. Skipped on Windows and Linux.
# The icon file "adaptive-learner.icns" is generated by the macOS CI workflow
# (iconutil is macOS-only) before PyInstaller runs. If the file is
# missing, the bundle builds without a custom icon and falls back to
# PyInstaller's default.
if sys.platform == "darwin":
    app = BUNDLE(
        exe,
        name="AdaptiveLearner Launcher.app",
        icon="adaptive-learner.icns" if os.path.exists("adaptive-learner.icns") else None,
        bundle_identifier="com.adaptive_learner.launcher",
        info_plist={
            "CFBundleName": "AdaptiveLearner Launcher",
            "CFBundleDisplayName": "AdaptiveLearner Launcher",
            "CFBundleVersion": "1.97.0",
            "CFBundleShortVersionString": "1.97.0",
            "NSHighResolutionCapable": True,
            "NSRequiresAquaSystemAppearance": False,
        },
    )
