"""Self-checks for the ``plugin-lock-paired-with-pyproject`` pre-commit hook.

The hook (``scripts/check_plugin_lock_paired.py``) guards the failure shape
documented in ``.claude/rules/lessons-learned.md`` "Two installation paths
diverge: ``make test`` vs per-plugin CI": a shared-dependency pin bumped in a
plugin's ``pyproject.toml`` without regenerating that plugin's own
``poetry.lock``, which turns the per-plugin CI job red while ``make test``
stays green.

#1903 adds the version-only carve-out: ``make sync-versions`` rewrites the
``version`` field of all 13 plugin pyprojects on every release, but poetry does
not fold that field into the lock's ``content-hash`` — ``poetry lock`` produces
an empty diff, so there is no lockfile to pair. The hook must let that through
WITHOUT weakening the dependency guard, which is the whole point of the
exercise: the carve-out is narrow, the safety net stays.

Each test builds a real throwaway git repo and stages real content, so the
hook is exercised through the same ``git diff --cached`` path it uses in
production rather than against mocked git output.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

HOOK = Path(__file__).resolve().parents[2] / "scripts" / "check_plugin_lock_paired.py"
PLUGIN_DIR = "plugins/adaptive-learner-plugin-demo"

BASE_PYPROJECT = """\
[tool.poetry]
name = "adaptive-learner-plugin-demo"
version = "2.4.0"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.136.0"
"""

BASE_LOCK = """\
# This file is autogenerated by Poetry.
content-hash = "deadbeef"
"""


def _git(repo: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(["git", *args], cwd=repo, check=True, capture_output=True, text=True)


def _run_hook(repo: Path, *paths: str) -> subprocess.CompletedProcess[str]:
    """Invoke the hook the way pre-commit does: staged paths as argv."""
    return subprocess.run(
        [sys.executable, str(HOOK), *paths],
        cwd=repo,
        capture_output=True,
        text=True,
    )


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    """A throwaway git repo with one committed plugin pyproject + lock."""
    _git(tmp_path, "init", "-q")
    _git(tmp_path, "config", "user.email", "test@example.com")
    _git(tmp_path, "config", "user.name", "Test")
    plugin = tmp_path / PLUGIN_DIR
    plugin.mkdir(parents=True)
    (plugin / "pyproject.toml").write_text(BASE_PYPROJECT, encoding="utf-8")
    (plugin / "poetry.lock").write_text(BASE_LOCK, encoding="utf-8")
    _git(tmp_path, "add", "-A")
    _git(tmp_path, "commit", "-qm", "seed")
    return tmp_path


def _stage_pyproject(repo: Path, content: str) -> None:
    (repo / PLUGIN_DIR / "pyproject.toml").write_text(content, encoding="utf-8")
    _git(repo, "add", f"{PLUGIN_DIR}/pyproject.toml")


# --- the guard that must NOT weaken (#1903 regression pin) -----------------


def test_dependency_change_without_lock_is_blocked(repo: Path) -> None:
    """A real dependency pin bump without its lock still fails the hook.

    This is the v0.30.0 red-on-main shape. #1903 must never make this pass.
    """
    _stage_pyproject(repo, BASE_PYPROJECT.replace("^0.136.0", "^0.137.0"))
    result = _run_hook(repo, f"{PLUGIN_DIR}/pyproject.toml")
    assert result.returncode == 1
    assert "without its paired poetry.lock" in result.stderr


def test_dependency_change_with_lock_passes(repo: Path) -> None:
    """The correct remediation — stage the regenerated lock too — passes."""
    _stage_pyproject(repo, BASE_PYPROJECT.replace("^0.136.0", "^0.137.0"))
    (repo / PLUGIN_DIR / "poetry.lock").write_text(
        BASE_LOCK.replace("deadbeef", "cafebabe"), encoding="utf-8"
    )
    _git(repo, "add", f"{PLUGIN_DIR}/poetry.lock")
    result = _run_hook(repo, f"{PLUGIN_DIR}/pyproject.toml")
    assert result.returncode == 0, result.stderr


def test_version_and_dependency_change_together_is_blocked(repo: Path) -> None:
    """A version bump does NOT launder an accompanying dependency change.

    The carve-out is per-diff, not per-file: if anything outside the version
    field moved, the lock is still required.
    """
    mixed = BASE_PYPROJECT.replace('version = "2.4.0"', 'version = "2.5.0"').replace(
        "^0.136.0", "^0.137.0"
    )
    _stage_pyproject(repo, mixed)
    result = _run_hook(repo, f"{PLUGIN_DIR}/pyproject.toml")
    assert result.returncode == 1


# --- the #1903 carve-out ---------------------------------------------------


def test_version_only_bump_passes_without_lock(repo: Path) -> None:
    """A release bump touching only ``version`` needs no paired lock.

    ``make sync-versions`` rewrites this field in all 13 plugin pyprojects on
    every release; poetry keeps it out of the lock content-hash, so
    ``make lock-all-plugins`` yields an empty diff and there is nothing to
    stage alongside.
    """
    _stage_pyproject(repo, BASE_PYPROJECT.replace('version = "2.4.0"', 'version = "2.5.0"'))
    result = _run_hook(repo, f"{PLUGIN_DIR}/pyproject.toml")
    assert result.returncode == 0, result.stderr


def test_version_only_bump_across_several_plugins_passes(repo: Path) -> None:
    """The release shape: every plugin bumped at once, no locks staged."""
    second = "plugins/adaptive-learner-plugin-other"
    (repo / second).mkdir(parents=True)
    (repo / second / "pyproject.toml").write_text(BASE_PYPROJECT, encoding="utf-8")
    (repo / second / "poetry.lock").write_text(BASE_LOCK, encoding="utf-8")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-qm", "second plugin")

    bumped = BASE_PYPROJECT.replace('version = "2.4.0"', 'version = "2.5.0"')
    _stage_pyproject(repo, bumped)
    (repo / second / "pyproject.toml").write_text(bumped, encoding="utf-8")
    _git(repo, "add", f"{second}/pyproject.toml")

    result = _run_hook(repo, f"{PLUGIN_DIR}/pyproject.toml", f"{second}/pyproject.toml")
    assert result.returncode == 0, result.stderr


# --- boundary + defensive --------------------------------------------------


def test_new_plugin_pyproject_requires_lock(repo: Path) -> None:
    """An added (not modified) pyproject has no version-only diff to trust."""
    new_dir = repo / "plugins/adaptive-learner-plugin-fresh"
    new_dir.mkdir(parents=True)
    (new_dir / "pyproject.toml").write_text(BASE_PYPROJECT, encoding="utf-8")
    _git(repo, "add", "plugins/adaptive-learner-plugin-fresh/pyproject.toml")
    result = _run_hook(repo, "plugins/adaptive-learner-plugin-fresh/pyproject.toml")
    assert result.returncode == 1


def test_no_arguments_is_a_no_op(repo: Path) -> None:
    """No matching staged file — nothing to check."""
    assert _run_hook(repo).returncode == 0


def test_nothing_staged_is_a_no_op(repo: Path) -> None:
    """``pre-commit run --all-files`` passes argv but stages nothing."""
    result = _run_hook(repo, f"{PLUGIN_DIR}/pyproject.toml")
    assert result.returncode == 0, result.stderr
