"""Identity persistence service (Phase 41).

Writes a small YAML file at ``~/.config/adaptive_learner/identity.yaml``
that survives a browser data wipe and lets the frontend recover the
"who am I" state after every localStorage / IndexedDB / cookie store
is cleared. Same directory as ``secrets.yaml``; same 0o600 perms;
same platformdirs-based resolver.

File shape::

    # Auto-generated by Adaptive Learner. Do not edit manually.
    # Last written: 2026-05-23T14:30:00+00:00
    active_project_id: 86071d42-653f-4827-a4e5-242207f3c2ab
    language: de
    last_seen: '2026-05-23T14:30:00+00:00'
    user_id: d2a7e8dd-078b-4489-852c-d2ab87c1d589

Public surface:

- :func:`get_identity_path`: canonical Path (used by tests + the
  Settings UI in 41D).
- :func:`load_identity`: returns the parsed dict or None.
- :func:`update_identity`: merge-style writer; partial fields are
  preserved from the existing file.
- :func:`clear_identity`: best-effort file delete (for the Reset
  action in 41D / 41F).

The writer is the only place that touches the filesystem; callers
in :mod:`app.services.users` + :mod:`app.services.projects` hook
into it AFTER their DB commit so a 5xx during the file write does
not roll back the legitimate domain change.
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

from app.paths import get_config_dir

logger = logging.getLogger(__name__)

IDENTITY_FILENAME = "identity.yaml"
_REQUIRED_FIELDS = ("user_id",)


def get_identity_path() -> Path:
    """Canonical ``~/.config/adaptive_learner/identity.yaml`` path.

    Always resolved fresh via :func:`app.paths.get_config_dir` so the
    ``ADAPTIVE_LEARNER_CONFIG_DIR`` env-var override applies in tests +
    Docker without re-importing this module.
    """
    return get_config_dir() / IDENTITY_FILENAME


def load_identity() -> dict[str, Any] | None:
    """Return the parsed identity dict, or ``None`` when missing.

    Returns ``None`` on every read failure (file missing, malformed
    YAML, missing required ``user_id`` field) and logs the reason.
    The caller treats every non-dict result as "no identity" and
    falls back to the onboarding path.
    """
    path = get_identity_path()
    if not path.is_file():
        return None
    try:
        raw = path.read_text(encoding="utf-8")
        data = yaml.safe_load(raw)
    except (OSError, yaml.YAMLError) as exc:
        logger.warning("identity.yaml read failed: %s", exc)
        return None
    if not isinstance(data, dict):
        logger.warning("identity.yaml top-level is %s, expected dict", type(data).__name__)
        return None
    for field in _REQUIRED_FIELDS:
        if field not in data:
            logger.warning("identity.yaml missing required field %r", field)
            return None
    return data


def update_identity(
    *,
    user_id: str,
    project_id: str | None = None,
    language: str | None = None,
) -> None:
    """Merge fields into ``identity.yaml`` and refresh ``last_seen``.

    ``user_id`` is always required (every identity has an owner).
    ``project_id`` and ``language`` are optional - ``None`` means
    "leave the existing value alone", not "clear it". To wipe the
    file entirely use :func:`clear_identity`.

    Best-effort: if the write fails (permissions, disk full), the
    error is logged and swallowed. The caller's DB commit has
    already succeeded; we do not want a config-file write to
    propagate a 500 back to the API client.
    """
    existing = load_identity() or {}
    merged: dict[str, Any] = dict(existing)
    merged["user_id"] = user_id
    if project_id is not None:
        merged["active_project_id"] = project_id
    if language is not None:
        merged["language"] = language
    merged["last_seen"] = datetime.now(UTC).isoformat()
    try:
        _write_identity(merged)
    except OSError as exc:
        logger.warning("identity.yaml write failed: %s", exc)


def clear_identity() -> None:
    """Remove ``identity.yaml`` if present; no-op otherwise.

    Used by the Settings Reset action (Phase 41D / 41F) before the
    frontend clears localStorage + reloads.
    """
    path = get_identity_path()
    path.unlink(missing_ok=True)


def _write_identity(data: dict[str, Any]) -> None:
    """Atomically write the identity dict with 0o600 permissions.

    ``yaml.safe_dump`` with ``sort_keys=True`` keeps the file diff-
    stable across writes; the explicit comment header reminds anyone
    who opens it that hand-edits will be overwritten. The chmod is
    POSIX-only; Windows ignores it but the platformdirs path is
    inside the user profile so OS-level ACLs already restrict it.
    """
    path = get_identity_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(data, sort_keys=True, allow_unicode=True)
    header = (
        "# Auto-generated by Adaptive Learner. Do not edit manually.\n"
        f"# Last written: {data.get('last_seen', '')}\n"
    )
    path.write_text(header + body, encoding="utf-8")
    try:
        path.chmod(0o600)
    except OSError as exc:  # pragma: no cover - Windows / non-POSIX
        logger.warning("chmod 0600 failed for %s: %s", path, exc)


__all__ = [
    "IDENTITY_FILENAME",
    "clear_identity",
    "get_identity_path",
    "load_identity",
    "update_identity",
]
