/**
 * Reproducible app-icon generation (v1.87.0 branding refresh, #715).
 *
 * Generates the complete icon set (favicon, PWA, maskable, apple-touch,
 * Open-Graph preview) from a single high-resolution source mark so the
 * branding can be regenerated byte-for-byte whenever the source changes.
 *
 * Source: ``frontend/branding/adaptive-learner-mark.png`` (the teal
 * "leaf / dispersing-dots" mark on white, 1024x1024). The script trims
 * to the mark's content box, recenters it, and re-pads per target so the
 * off-centre source composition does not propagate into the outputs.
 *
 * Outputs (all written to ``frontend/public/``):
 *   favicon-16x16.png, favicon-32x32.png   browser tab (transparent)
 *   favicon.ico                            legacy multi-size (16+32+48)
 *   apple-touch-icon.png (180)             iOS home screen (opaque white)
 *   icon-192.png, icon-512.png             PWA + in-app header (transparent)
 *   maskable-icon-512x512.png              Android maskable (white, inner safe zone)
 *   og-image.png (1200x630)                social preview (text + mark)
 *
 * Run: ``node scripts/generate-icons.mjs`` from ``frontend/``
 * (also wired as the ``gen:icons`` npm script).
 */
import sharp from "sharp";
import pngToIco from "png-to-ico";
import {fileURLToPath} from "node:url";
import {dirname, resolve} from "node:path";
import {writeFile, mkdir} from "node:fs/promises";

const HERE = dirname(fileURLToPath(import.meta.url));
const FRONTEND = resolve(HERE, "..");
const SOURCE = resolve(FRONTEND, "branding/adaptive-learner-mark.png");
const OUT = resolve(FRONTEND, "public");

/** Brand palette derived from the source mark. */
const LEAF = "#16cfc2"; // the solid swoosh teal (sampled from the source)
const LEAF_RGB = {r: 0x16, g: 0xcf, b: 0xc2};
const TILE_BG = {r: 255, g: 255, b: 255, alpha: 1}; // opaque white tile (matches the source design)
const TRANSPARENT = {r: 0, g: 0, b: 0, alpha: 0};
const OG_BG = "#f0fdfa"; // teal-50, light card background for the social preview
const OG_TEXT = "#0f766e"; // teal-700, accessible on the light card

/**
 * Detects the bounding box of the non-white mark in the source image.
 * The AI-generated source carries faint near-white noise, so a flat
 * sharp ``.trim()`` under-trims; this scans raw pixels with a tolerance.
 */
async function detectMarkBox(srcPath) {
    const {data, info} = await sharp(srcPath).ensureAlpha().raw().toBuffer({resolveWithObject: true});
    const {width, height, channels} = info;
    let minX = width, minY = height, maxX = 0, maxY = 0;
    for (let y = 0; y < height; y++) {
        for (let x = 0; x < width; x++) {
            const i = (y * width + x) * channels;
            const isWhite = data[i] > 232 && data[i + 1] > 232 && data[i + 2] > 232;
            if (!isWhite) {
                if (x < minX) minX = x;
                if (x > maxX) maxX = x;
                if (y < minY) minY = y;
                if (y > maxY) maxY = y;
            }
        }
    }
    const bleed = 6; // keep anti-aliased edges
    const left = Math.max(0, minX - bleed);
    const top = Math.max(0, minY - bleed);
    return {
        left,
        top,
        width: Math.min(width - left, maxX - minX + 1 + bleed * 2),
        height: Math.min(height - top, maxY - minY + 1 + bleed * 2),
    };
}

/**
 * Keys the white source background out and flattens the mark to flat
 * brand teal with a coverage-based alpha. The source mark is a single
 * teal (``LEAF``) on white, so every visible pixel becomes pure brand
 * teal with smooth anti-aliasing — it composites cleanly on ANY
 * background (dark header, white tile, light card) with no white box
 * and no light halo. Coverage is derived from the red channel: white
 * has high red, teal has low red, so ``(255 - r)`` is the mark coverage.
 *
 * @returns {Promise<{data: Buffer, info: {width: number, height: number}}>}
 */
async function keyedTealMark(srcPath, box) {
    const {data, info} = await sharp(srcPath)
        .extract(box)
        .ensureAlpha()
        .raw()
        .toBuffer({resolveWithObject: true});
    const {width, height, channels} = info;
    const out = Buffer.alloc(width * height * 4);
    for (let p = 0, q = 0; p < data.length; p += channels, q += 4) {
        const coverage = Math.min(255, Math.round((255 - data[p]) * 1.4));
        out[q] = LEAF_RGB.r;
        out[q + 1] = LEAF_RGB.g;
        out[q + 2] = LEAF_RGB.b;
        out[q + 3] = coverage;
    }
    return sharp(out, {raw: {width, height, channels: 4}}).png().toBuffer();
}

/**
 * Builds one square icon: the trimmed mark fitted into ``size`` with
 * the given fractional margin, centred on the given background.
 */
async function buildSquare({mark, size, margin, background}) {
    const content = Math.round(size * (1 - margin * 2));
    const fitted = await sharp(mark)
        .resize(content, content, {fit: "inside", background: TRANSPARENT})
        .toBuffer({resolveWithObject: true});
    return sharp({
        create: {width: size, height: size, channels: 4, background},
    })
        .composite([
            {
                input: fitted.data,
                left: Math.round((size - fitted.info.width) / 2),
                top: Math.round((size - fitted.info.height) / 2),
            },
        ])
        .png()
        .toBuffer();
}

async function main() {
    await mkdir(OUT, {recursive: true});
    const box = await detectMarkBox(SOURCE);
    // The recentred, tightly-cropped mark, white keyed out, flattened to
    // flat brand teal on transparent so it composites on any background.
    const mark = await keyedTealMark(SOURCE, box);

    const transparentTargets = [
        {name: "favicon-16x16.png", size: 16, margin: 0.04},
        {name: "favicon-32x32.png", size: 32, margin: 0.04},
        {name: "icon-192.png", size: 192, margin: 0.06},
        {name: "icon-512.png", size: 512, margin: 0.06},
    ];
    for (const t of transparentTargets) {
        const buf = await buildSquare({mark, size: t.size, margin: t.margin, background: TRANSPARENT});
        await writeFile(resolve(OUT, t.name), buf);
        console.log(`  ${t.name} (${t.size}x${t.size}, transparent)`);
    }

    // apple-touch-icon: iOS composites transparency onto black, so use an opaque white tile.
    const apple = await buildSquare({mark, size: 180, margin: 0.1, background: TILE_BG});
    await writeFile(resolve(OUT, "apple-touch-icon.png"), apple);
    console.log("  apple-touch-icon.png (180x180, white)");

    // maskable: mark kept inside the inner ~74% so circular/round-rect masks never clip it.
    const maskable = await buildSquare({mark, size: 512, margin: 0.13, background: TILE_BG});
    await writeFile(resolve(OUT, "maskable-icon-512x512.png"), maskable);
    console.log("  maskable-icon-512x512.png (512x512, white, safe zone)");

    // favicon.ico: multi-size from the transparent renders.
    const ico = await pngToIco([
        await buildSquare({mark, size: 16, margin: 0.04, background: TRANSPARENT}),
        await buildSquare({mark, size: 32, margin: 0.04, background: TRANSPARENT}),
        await buildSquare({mark, size: 48, margin: 0.06, background: TRANSPARENT}),
    ]);
    await writeFile(resolve(OUT, "favicon.ico"), ico);
    console.log("  favicon.ico (16+32+48)");

    // og-image: light brand card with the mark on the left and the wordmark on the right.
    const ogW = 1200, ogH = 630;
    const ogMarkSize = 360;
    const ogMark = await sharp(mark)
        .resize(ogMarkSize, ogMarkSize, {fit: "inside", background: TRANSPARENT})
        .toBuffer({resolveWithObject: true});
    const ogCard = Buffer.from(
        `<svg xmlns="http://www.w3.org/2000/svg" width="${ogW}" height="${ogH}">
            <rect width="${ogW}" height="${ogH}" fill="${OG_BG}"/>
            <rect x="0" y="0" width="${ogW}" height="10" fill="${LEAF}"/>
            <text x="560" y="300" font-family="Inter, Segoe UI, Helvetica, Arial, sans-serif"
                  font-size="66" font-weight="700" fill="${OG_TEXT}">Adaptive Learner</text>
            <text x="562" y="356" font-family="Inter, Segoe UI, Helvetica, Arial, sans-serif"
                  font-size="32" font-weight="400" fill="#0f2e2c">Learn the way you learn best</text>
        </svg>`,
    );
    const og = await sharp(ogCard)
        .composite([
            {
                input: ogMark.data,
                left: Math.round(150 + (ogMarkSize - ogMark.info.width) / 2),
                top: Math.round((ogH - ogMark.info.height) / 2),
            },
        ])
        .png()
        .toBuffer();
    await writeFile(resolve(OUT, "og-image.png"), og);
    console.log("  og-image.png (1200x630)");

    console.log("Icon set generated in frontend/public/");
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
