/**
 * Labels — every user-visible string the renderer emits
 * (Phase 49C / v1.32.0 / PHASE-42-STORAGE-ABSTRACTION-01).
 *
 * Mirrors the Python ``Labels`` dataclass at
 * ``plugins/.../learning-repo/adaptive_learner_learning_repo/
 * labels.py`` — field-for-field with the same English
 * defaults so a missing i18n key falls back to identical text
 * on either side.
 *
 * The ``labelsFor(language)`` factory reads the bundled
 * ``frontend/src/data/i18n/{lang}.json`` (regenerated by
 * ``scripts/sync_i18n_to_frontend.py`` from the canonical
 * backend YAML catalogs) and overlays the ``repo.{field}``
 * keys onto the defaults. Identical contract to the Python
 * ``labels_for(language)``: missing keys fall back, malformed
 * input returns defaults.
 */

// --- The label record --------------------------------------------------

/**
 * Every string the renderer emits, grouped by meta-file. The
 * ``{topic}``-style placeholders are substituted by the
 * renderer via ``formatLabel``. Default values exactly match
 * the Python ``@dataclass(frozen=True)`` defaults — the
 * parity test (49F) pins byte-for-byte output on shared
 * input.
 */
export interface Labels {
    // README.md
    readme_title: string;
    readme_goal_heading: string;
    readme_status_heading: string;
    readme_active: string;
    readme_archived: string;
    readme_progress_heading: string;
    readme_sessions_label: string;
    readme_cycles_label: string;
    readme_method_distribution_heading: string;
    readme_topics_heading: string;
    readme_no_topics: string;
    readme_see_also_heading: string;
    readme_see_stats: string;
    readme_see_cheatsheet: string;
    readme_see_roadmap: string;

    // LEARNING_STATS.md
    stats_title: string;
    stats_intro: string;
    stats_no_sessions: string;
    stats_sessions_heading: string;
    stats_table_session: string;
    stats_table_method: string;
    stats_table_understanding: string;
    stats_table_transfer: string;
    stats_table_stress: string;
    stats_table_cycles: string;
    stats_table_status: string;
    stats_method_switches_heading: string;
    stats_no_method_switches: string;
    stats_table_from: string;
    stats_table_to: string;
    stats_table_reason: string;
    stats_table_when: string;
    stats_exit_threshold_heading: string;
    stats_exit_threshold_body: string;
    stats_exit_pin_marker: string;

    // CHEATSHEET.md
    cheatsheet_title: string;
    cheatsheet_intro: string;
    cheatsheet_notes_heading: string;
    cheatsheet_meta_learning_heading: string;
    cheatsheet_no_notes: string;
    cheatsheet_no_meta_learning: string;

    // ROADMAP.md
    roadmap_title: string;
    roadmap_intro: string;
    roadmap_next_steps_heading: string;
    roadmap_no_next_steps: string;
    roadmap_resume_active: string;
    roadmap_start_first: string;
    roadmap_start_next: string;
    roadmap_open_topics_heading: string;
    roadmap_no_open_topics: string;

    // Topic folder stub README.md
    topic_readme_title: string;
    topic_readme_sessions_heading: string;
    topic_readme_methods_heading: string;
    topic_readme_parent_link: string;
    topic_readme_no_sessions: string;
}

// --- English defaults (mirror Python dataclass defaults) ---------------

export const DEFAULT_LABELS: Labels = {
    // README.md
    readme_title: "Learning Project: {topic}",
    readme_goal_heading: "Goal",
    readme_status_heading: "Status",
    readme_active: "active",
    readme_archived: "archived",
    readme_progress_heading: "Progress",
    readme_sessions_label: "Sessions",
    readme_cycles_label: "Cycles",
    readme_method_distribution_heading: "Method distribution",
    readme_topics_heading: "Topics",
    readme_no_topics: "_No topics traversed yet._",
    readme_see_also_heading: "See also",
    readme_see_stats:
        "[LEARNING_STATS.md](LEARNING_STATS.md) - error rates, understanding, transfer, intervention log.",
    readme_see_cheatsheet:
        "[CHEATSHEET.md](CHEATSHEET.md) - distilled notes + Meta-Learning Insights.",
    readme_see_roadmap: "[ROADMAP.md](ROADMAP.md) - next steps.",

    // LEARNING_STATS.md
    stats_title: "Learning Statistics",
    stats_intro:
        "Per-session metrics derived from `step_evaluations`, `session_ratings`, and `method_switches`. Generated automatically - do not edit by hand.",
    stats_no_sessions: "_No sessions yet._",
    stats_sessions_heading: "Sessions",
    stats_table_session: "Session",
    stats_table_method: "Method",
    stats_table_understanding: "Understanding",
    stats_table_transfer: "Transfer",
    stats_table_stress: "Stress",
    stats_table_cycles: "Cycles",
    stats_table_status: "Status",
    stats_method_switches_heading: "Method switches",
    stats_no_method_switches: "_No method switches recorded._",
    stats_table_from: "From",
    stats_table_to: "To",
    stats_table_reason: "Reason",
    stats_table_when: "When",
    stats_exit_threshold_heading: "Exit thresholds",
    stats_exit_threshold_body:
        "Per the *Von Theorie zur Praxis* Article 1 § 8: a topic is considered mastered when Understanding ≥ 9/10 AND Transfer ≥ 8/10 stable over 2 consecutive cycles. The renderer pins the corresponding session row when both conditions hold.",
    stats_exit_pin_marker: "✅ exit threshold met",

    // CHEATSHEET.md
    cheatsheet_title: "Cheatsheet",
    cheatsheet_intro:
        'Distilled notes from your sessions. The **Meta-Learning Insights** section collects notes tagged `kind="meta_learning"` - observations about *how* you learn best (per the Article-3 pattern).',
    cheatsheet_notes_heading: "Notes",
    cheatsheet_meta_learning_heading: "Meta-Learning Insights",
    cheatsheet_no_notes: "_No notes yet._",
    cheatsheet_no_meta_learning:
        '_No meta-learning insights yet. Add a `SessionNote` with `kind="meta_learning"` to record an observation about your learning process._',

    // ROADMAP.md
    roadmap_title: "Roadmap",
    roadmap_intro: "Open topics + recommended next steps.",
    roadmap_next_steps_heading: "Next steps",
    roadmap_no_next_steps:
        "_No active project - start a new session to populate this list._",
    roadmap_resume_active:
        "Resume the active session (method: **{method}**, step {step}/7, cycle {cycle}).",
    roadmap_start_first:
        "Start your first learning session - the assessment recommends starting with method **{method}**.",
    roadmap_start_next:
        "Start the next session - last completed session used method **{method}**.",
    roadmap_open_topics_heading: "Open topics",
    roadmap_no_open_topics: "_No topics defined yet._",

    // Topic folder stub README.md
    topic_readme_title: "Topic: {title}",
    topic_readme_sessions_heading: "Sessions on this topic",
    topic_readme_methods_heading: "Methods used",
    topic_readme_parent_link: "← [Project root](../README.md)",
    topic_readme_no_sessions: "_No sessions traversed this topic._",
};

// --- Factory ----------------------------------------------------------

/**
 * Return the Labels bundle for ``language``. Overlay
 * ``repo.{field}`` entries from the bundled i18n catalog onto
 * the English defaults. Missing keys / missing language /
 * malformed catalog fall back silently — matches the Python
 * factory's robustness contract.
 *
 * The bundled JSON catalogs at
 * ``frontend/src/data/i18n/{lang}.json`` are the source of
 * truth at runtime in Dexie mode; they are regenerated from
 * the backend YAML by ``scripts/sync_i18n_to_frontend.py``
 * (drift-pinned by ``i18n-sync.test.ts``).
 */
export async function labelsFor(language: string): Promise<Labels> {
    // Lazy (non-eager) glob: each language catalog is its own
    // chunk fetched on demand, shared with ``dexieStorage.i18n.get``.
    // Eager loading pulled all 8 catalogs into the consuming chunk —
    // see docs/audits/performance-audit-2026-06-03.md F-1.
    // Stryker disable all: static arguments required by Vite's import.meta.glob
    // macro; mutating any part breaks the vite:import-glob parser (#1956).
    const catalogs = import.meta.glob<Record<string, unknown>>(
        "../../data/i18n/*.json",
        {import: "default"},
    );
    // Stryker restore all
    const loader =
        catalogs[`../../data/i18n/${language}.json`] ??
        catalogs["../../data/i18n/en.json"];
    const catalog = loader ? await loader() : undefined;
    if (!catalog) {
        return {...DEFAULT_LABELS};
    }
    const repoBlock = catalog.repo;
    if (!repoBlock || typeof repoBlock !== "object" || Array.isArray(repoBlock)) {
        return {...DEFAULT_LABELS};
    }
    const overrides = repoBlock as Record<string, unknown>;
    const merged: Labels = {...DEFAULT_LABELS};
    for (const key of Object.keys(DEFAULT_LABELS) as (keyof Labels)[]) {
        const value = overrides[key as string];
        if (typeof value === "string") {
            merged[key] = value;
        }
    }
    return merged;
}

// --- Placeholder helper -----------------------------------------------

/**
 * Substitute ``{name}`` placeholders in a label template.
 * Mirrors Python's ``str.format(**kwargs)`` for the limited
 * subset the renderer uses (named, single-level, no format
 * specifiers).
 *
 * Unknown placeholders are left untouched — matches Python's
 * behaviour of raising ``KeyError`` only when the placeholder
 * is referenced and missing; here we silently skip to keep
 * the renderer robust against label-template typos.
 */
export function formatLabel(
    template: string,
    values: Record<string, string | number>,
): string {
    return template.replace(
        /\{(\w+)\}/g,
        (match, name: string) => {
            const v = values[name];
            return v === undefined ? match : String(v);
        },
    );
}
