/**
 * Cross-renderer parity (Phase 49F / v1.32.0 /
 * PHASE-42-STORAGE-ABSTRACTION-01).
 *
 * The TypeScript renderer in this directory MUST produce
 * byte-identical Markdown to the Python renderer when both
 * are given the same RenderContext data. The Python parity
 * test at
 * ``plugins/.../learning-repo/tests/test_parity.py`` pins the
 * Python side; this test pins the TS side. Both compare
 * against the SAME golden files at
 * ``tests/fixtures/learning-repo-parity/expected/`` so a
 * regression in either renderer surfaces as a test failure
 * on the other side until both converge.
 *
 * Golden files are generated by the Python renderer (set
 * ``LEARNING_REPO_PARITY_REGEN=1`` and re-run the Python
 * test). When a renderer change is intentional, regenerate
 * + commit + watch for the TS side to drift; fix until it
 * matches.
 *
 * Reads from the filesystem via Node's ``fs`` — works in
 * Vitest's node environment with no extra setup.
 */

import {readFileSync, readdirSync, statSync} from "node:fs";
import {join, relative, sep} from "node:path";

import {describe, expect, it} from "vitest";

import {buildRenderContext} from "./render-context";
import type {
    MethodSwitchData,
    ProjectData,
    RatingData,
    SessionData,
    SessionNoteData,
    StepEvaluationData,
} from "./render-context";
import {renderRepository} from "./renderer";

// Walk up: __dirname = frontend/src/lib/learning-repo
// repo root = ../../../..
const REPO_ROOT = join(__dirname, "..", "..", "..", "..");
const FIXTURE_DIR = join(
    REPO_ROOT,
    "tests",
    "fixtures",
    "learning-repo-parity",
);
const INPUT_PATH = join(FIXTURE_DIR, "input.json");
const EXPECTED_DIR = join(FIXTURE_DIR, "expected");

interface ParityFixture {
    rendered_at: string;
    project: ProjectData;
    sessions: SessionData[];
    ratings: RatingData[];
    step_evaluations: StepEvaluationData[];
    method_switches: MethodSwitchData[];
    notes: SessionNoteData[];
}

function loadFixture(): ParityFixture {
    return JSON.parse(readFileSync(INPUT_PATH, "utf-8"));
}

function listMarkdownGoldens(root: string): string[] {
    const out: string[] = [];
    function walk(dir: string): void {
        for (const entry of readdirSync(dir)) {
            const full = join(dir, entry);
            const stat = statSync(full);
            if (stat.isDirectory()) {
                walk(full);
            } else if (entry.endsWith(".md")) {
                // Use forward slashes on every platform so
                // the comparison matches the renderer's
                // ``{folder}/README.md`` shape on Windows
                // too.
                out.push(relative(root, full).split(sep).join("/"));
            }
        }
    }
    walk(root);
    return out.sort();
}

describe("learning-repo cross-renderer parity", () => {
    it("TS renderer matches every golden file", async () => {
        const data = loadFixture();
        const ctx = buildRenderContext({
            project: data.project,
            sessions: data.sessions,
            ratings: data.ratings,
            step_evaluations: data.step_evaluations,
            method_switches: data.method_switches,
            notes: data.notes,
            rendered_at: data.rendered_at,
        });
        const tree = await renderRepository(ctx, "en");

        for (const [path, content] of Object.entries(tree)) {
            const goldenPath = join(EXPECTED_DIR, path);
            const expected = readFileSync(goldenPath, "utf-8");
            // The error message names the path so a single
            // failed file is identifiable without grepping
            // through the whole tree.
            if (content !== expected) {
                throw new Error(
                    `Parity drift in ${path}:\n` +
                        `--- expected (golden, from Python renderer) ---\n` +
                        expected +
                        `--- got (TS renderer) ---\n` +
                        content,
                );
            }
            expect(content).toBe(expected);
        }
    });

    it("the golden file set matches the renderer output keys", async () => {
        const data = loadFixture();
        const ctx = buildRenderContext({
            project: data.project,
            sessions: data.sessions,
            ratings: data.ratings,
            step_evaluations: data.step_evaluations,
            method_switches: data.method_switches,
            notes: data.notes,
            rendered_at: data.rendered_at,
        });
        const tree = await renderRepository(ctx, "en");
        const renderedPaths = Object.keys(tree).sort();
        const goldenPaths = listMarkdownGoldens(EXPECTED_DIR);
        // If this asserts, either a renderer added a new
        // file without a matching golden, or a golden
        // exists that the renderer no longer produces.
        expect(goldenPaths).toEqual(renderedPaths);
    });
});
