/**
 * Pure tests for topic-folder-slug.ts (Phase 49C / v1.32.0 /
 * PHASE-42-STORAGE-ABSTRACTION-01).
 *
 * Mirrors the Python ``_topic_folder_name`` contract from
 * ``plugins/.../learning-repo/adaptive_learner_learning_repo/
 * meta/readme.py:69``. Same numbered-phase folder name shape
 * (``NN_slug``) — required for the README's topic links to
 * resolve to the topic-folder stubs generated by 49D.
 */

import {describe, expect, it} from "vitest";

import {topicFolderName} from "./topic-folder-slug";

describe("topicFolderName", () => {
    it("zero-pads single-digit order", () => {
        expect(topicFolderName(1, "Verbs")).toBe("01_verbs");
        expect(topicFolderName(9, "Verbs")).toBe("09_verbs");
    });

    it("preserves order at 10+ without truncating", () => {
        expect(topicFolderName(10, "Verbs")).toBe("10_verbs");
        expect(topicFolderName(99, "Verbs")).toBe("99_verbs");
        expect(topicFolderName(100, "Verbs")).toBe("100_verbs");
    });

    it("lowercases ASCII letters", () => {
        expect(topicFolderName(1, "VERBS")).toBe("01_verbs");
        expect(topicFolderName(1, "MixedCase")).toBe("01_mixedcase");
    });

    it("replaces non-alphanumeric chars with underscores", () => {
        expect(topicFolderName(1, "Verbs & Tenses")).toBe(
            "01_verbs_tenses",
        );
        expect(topicFolderName(1, "Hello, World!")).toBe(
            "01_hello_world",
        );
    });

    it("collapses runs of underscores", () => {
        expect(topicFolderName(1, "a -- b")).toBe("01_a_b");
        expect(topicFolderName(1, "x !!! y")).toBe("01_x_y");
    });

    it("strips leading + trailing underscores", () => {
        expect(topicFolderName(1, " spaces ")).toBe("01_spaces");
        expect(topicFolderName(1, "!?Verbs?!")).toBe("01_verbs");
    });

    it("defaults to 'topic' when slug is empty", () => {
        expect(topicFolderName(1, "")).toBe("01_topic");
        expect(topicFolderName(1, "!!!???")).toBe("01_topic");
        expect(topicFolderName(1, "   ")).toBe("01_topic");
    });

    it("preserves digits", () => {
        expect(topicFolderName(1, "Topic 2")).toBe("01_topic_2");
        expect(topicFolderName(1, "Chapter 7B")).toBe("01_chapter_7b");
    });

    it("handles unicode letters (Cyrillic, Greek, CJK)", () => {
        // Mirrors Python's Unicode-aware ``str.isalnum``.
        expect(topicFolderName(1, "Привет Мир")).toBe(
            "01_привет_мир",
        );
        expect(topicFolderName(1, "Γειά σου")).toBe("01_γειά_σου");
        expect(topicFolderName(1, "你好 世界")).toBe("01_你好_世界");
    });
});
