#!/usr/bin/env python3
"""Generate the complete endpoint list of the help API reference (#3454).

Single writer for ``docs/help/{en,de}/api/endpoints.md``. The list is
rendered from the committed OpenAPI snapshot (``schema/openapi.json``,
written by ``scripts/sync_openapi.py``), so it names every core router and
every plugin route and cannot fall behind them the way the hand-written
pages did. ``core-endpoints.md`` and ``plugin-endpoints.md`` keep the
worked examples; this page is the complete list.

Run from the repo root (``make sync-openapi`` runs it after the snapshot)::

    python3 scripts/generate_api_reference.py          # write both pages
    python3 scripts/generate_api_reference.py --check  # exit 1 on drift

Gate contract (quality-checks.md "Gate test contract"): a missing or
unreadable snapshot, or one with no operations, exits 2 instead of
rendering an empty page, and every run prints how many operations and
areas it rendered.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Protocol

CHECK = "api-reference"
EXIT_DRIFT = 1
EXIT_FAIL_CLOSED = 2

SNAPSHOT = Path("schema") / "openapi.json"
METHOD_ORDER = ("get", "post", "put", "patch", "delete")
UNTAGGED = "Other"

TEXT = {
    "en": {
        "title": "All endpoints",
        "intro": (
            "Every endpoint of the backend and its plugins, grouped by area.\n"
            "This page is generated from the OpenAPI snapshot\n"
            "`schema/openapi.json` by `scripts/generate_api_reference.py`;\n"
            "do not edit it by hand. The request and response schemas of each\n"
            "endpoint are in that snapshot, or at `/openapi.json` on a running\n"
            "backend. Worked examples: [Core endpoints](core-endpoints.md) and\n"
            "[Plugin endpoints](plugin-endpoints.md)."
        ),
        "header": "| Method | Path | Summary |",
        "deprecated": "(deprecated)",
    },
    "de": {
        "title": "Alle Endpoints",
        "intro": (
            "Jeder Endpoint des Backends und seiner Plugins, nach Bereich\n"
            "gruppiert. Diese Seite wird von `scripts/generate_api_reference.py`\n"
            "aus dem OpenAPI-Snapshot `schema/openapi.json` erzeugt; nicht von\n"
            "Hand bearbeiten. Die Request- und Response-Schemas jedes Endpoints\n"
            "stehen in diesem Snapshot oder unter `/openapi.json` eines laufenden\n"
            "Backends. Ausgearbeitete Beispiele: [Core-Endpoints](core-endpoints.md)\n"
            "und [Plugin-Endpoints](plugin-endpoints.md)."
        ),
        "header": "| Methode | Pfad | Zusammenfassung |",
        "deprecated": "(veraltet)",
    },
}

GENERATED_MARKER = (
    "<!-- Generated by scripts/generate_api_reference.py from schema/openapi.json; "
    "do not edit by hand (#3454). -->"
)


def operations(spec: dict) -> list[tuple[str, str, str, dict]]:
    """Every operation of the spec as ``(tag, method, path, operation)``.

    An operation with several tags is listed under its first; one without
    a tag lands under ``Other``.

    Args:
        spec: The parsed OpenAPI document.

    Returns:
        The operations sorted by tag, then path, then HTTP method order.
    """
    rows = []
    for path, item in spec.get("paths", {}).items():
        for method, operation in item.items():
            if method not in METHOD_ORDER:
                continue
            tag = (operation.get("tags") or [UNTAGGED])[0]
            rows.append((tag, method, path, operation))
    return sorted(rows, key=lambda r: (r[0].lower(), r[2], METHOD_ORDER.index(r[1])))


def _cell(text: str) -> str:
    """One Markdown table cell: pipes escaped, line breaks folded."""
    return " ".join(text.split()).replace("|", "\\|")


def render(spec: dict, lang: str) -> str:
    """Render the endpoint page for one help language.

    Args:
        spec: The parsed OpenAPI document.
        lang: A key of ``TEXT`` (``"en"`` or ``"de"``).

    Returns:
        The complete Markdown page, ending in a newline.
    """
    text = TEXT[lang]
    lines = [GENERATED_MARKER, "", f"# {text['title']}", "", text["intro"]]
    current = None
    for tag, method, path, operation in operations(spec):
        if tag != current:
            lines += ["", f"## {tag}", "", text["header"], "|---|---|---|"]
            current = tag
        summary = _cell(operation.get("summary") or operation.get("operationId") or "")
        if operation.get("deprecated"):
            summary = f"{summary} {text['deprecated']}"
        lines.append(f"| `{method.upper()}` | `{path}` | {summary} |")
    return "\n".join(lines) + "\n"


def page_path(repo: Path, lang: str) -> Path:
    """Where the generated page for ``lang`` lives."""
    return repo / "docs" / "help" / lang / "api" / "endpoints.md"


def read_spec(repo: Path) -> dict:
    """Read the committed snapshot and insist it holds operations.

    Raises:
        ValueError: when the snapshot is missing, unreadable, or holds no
            operation - the caller must treat that as a failure, never as
            "nothing to render".
    """
    path = repo / SNAPSHOT
    try:
        spec = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"cannot read {SNAPSHOT}: {exc}") from exc
    if not operations(spec):
        raise ValueError(f"{SNAPSHOT} holds no operation")
    return spec


def load_spec(repo: Path) -> dict:
    """:func:`read_spec` for the command line: exits 2 instead of raising.

    Raises:
        SystemExit: with ``EXIT_FAIL_CLOSED`` when the snapshot cannot be used.
    """
    try:
        return read_spec(repo)
    except ValueError as exc:
        print(f"api-reference: FAIL-CLOSED: {exc}")
        raise SystemExit(EXIT_FAIL_CLOSED) from exc


def stale_pages(repo: Path, spec: dict) -> list[Path]:
    """The generated pages whose content differs from a fresh render."""
    stale = []
    for lang in TEXT:
        path = page_path(repo, lang)
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != render(spec, lang):
            stale.append(path)
    return stale


class _Report(Protocol):
    def fail(self, check: str, message: str, fixed: bool = False) -> None: ...

    def note(self, message: str) -> None: ...


def check_api_reference(report: _Report, repo: Path) -> None:
    """``verify_docs`` check: the generated pages match the snapshot.

    A snapshot that cannot be read FAILs (#2287); the note says how many
    operations the comparison covered, so an empty basis never reads as
    a clean one.
    """
    try:
        spec = read_spec(repo)
    except ValueError as exc:
        report.fail(CHECK, f"{exc} (basis missing; #2287)")
        return
    report.note(f"{CHECK}: {len(operations(spec))} operations against {len(TEXT)} generated pages")
    for path in stale_pages(repo, spec):
        report.fail(
            CHECK,
            f"{path.relative_to(repo)} differs from {SNAPSHOT} - "
            "run python3 scripts/generate_api_reference.py and commit it",
        )


def _repo_root() -> Path:
    """Repo root from the working directory, never from ``__file__`` (worktrees)."""
    out = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True, check=False
    )
    if out.returncode != 0:
        print("api-reference: FAIL-CLOSED: not inside a git checkout")
        raise SystemExit(EXIT_FAIL_CLOSED)
    return Path(out.stdout.strip())


def main(argv: list[str]) -> int:
    """Write the pages, or with ``--check`` report drift."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 when a page is stale")
    opts = parser.parse_args(argv)

    repo = _repo_root()
    spec = load_spec(repo)
    ops = operations(spec)
    areas = len({tag for tag, *_ in ops})
    print(f"api-reference: {len(ops)} operations in {areas} areas from {SNAPSHOT}")

    stale = stale_pages(repo, spec)
    if opts.check:
        if stale:
            for path in stale:
                print(f"api-reference: DRIFT - {path.relative_to(repo)} differs from the snapshot")
            print("Run `python3 scripts/generate_api_reference.py` and commit the pages.")
            return EXIT_DRIFT
        print("api-reference: check OK - the pages match the snapshot")
        return 0
    for lang in TEXT:
        path = page_path(repo, lang)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(render(spec, lang), encoding="utf-8")
        print(f"api-reference: wrote {path.relative_to(repo)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
