/**
 * Anki collection.anki2 schema constants (Phase 30A).
 *
 * The Anki SQLite schema is well-documented (see Anki source +
 * the AnkiDroid wiki). For our use case — generating decks of
 * Basic + Cloze cards — we only need a minimal subset:
 *
 *   col     — collection metadata (one row)
 *   notes   — note table (one row per "card pair")
 *   cards   — card table (one row per scheduled card; Basic
 *             yields 1 card per note, Cloze yields N per note)
 *   revlog  — review log (always empty for an exported deck)
 *   graves  — deletion log (always empty)
 *
 * The ``col.models`` and ``col.decks`` blobs are JSON strings
 * carrying the model + deck definitions. Anki validates them
 * strictly on import; the constants below were derived from a
 * known-good empty .apkg generated by Anki 2.1 desktop.
 */

export const ANKI_SCHEMA_VERSION = 11;

/**
 * DDL for the collection.anki2 tables. Captured verbatim from
 * an Anki 2.1 export.
 */
export const COLLECTION_DDL = `
CREATE TABLE col (
    id              integer primary key,
    crt             integer not null,
    mod             integer not null,
    scm             integer not null,
    ver             integer not null,
    dty             integer not null,
    usn             integer not null,
    ls              integer not null,
    conf            text not null,
    models          text not null,
    decks           text not null,
    dconf           text not null,
    tags            text not null
);
CREATE TABLE notes (
    id              integer primary key,
    guid            text not null,
    mid             integer not null,
    mod             integer not null,
    usn             integer not null,
    tags            text not null,
    flds            text not null,
    sfld            integer not null,
    csum            integer not null,
    flags           integer not null,
    data            text not null
);
CREATE TABLE cards (
    id              integer primary key,
    nid             integer not null,
    did             integer not null,
    ord             integer not null,
    mod             integer not null,
    usn             integer not null,
    type            integer not null,
    queue           integer not null,
    due             integer not null,
    ivl             integer not null,
    factor          integer not null,
    reps            integer not null,
    lapses          integer not null,
    left            integer not null,
    odue            integer not null,
    odid            integer not null,
    flags           integer not null,
    data            text not null
);
CREATE TABLE revlog (
    id              integer primary key,
    cid             integer not null,
    usn             integer not null,
    ease            integer not null,
    ivl             integer not null,
    lastIvl         integer not null,
    factor          integer not null,
    time            integer not null,
    type            integer not null
);
CREATE TABLE graves (
    usn             integer not null,
    oid             integer not null,
    type            integer not null
);
CREATE INDEX ix_notes_usn on notes (usn);
CREATE INDEX ix_cards_usn on cards (usn);
CREATE INDEX ix_revlog_usn on revlog (usn);
CREATE INDEX ix_cards_nid on cards (nid);
CREATE INDEX ix_cards_sched on cards (did, queue, due);
CREATE INDEX ix_revlog_cid on revlog (cid);
CREATE INDEX ix_notes_csum on notes (csum);
`;

/** Anki ``col.conf`` baseline. */
export const DEFAULT_CONF = {
    nextPos: 1,
    estTimes: true,
    activeDecks: [1],
    sortType: "noteFld",
    timeLim: 0,
    sortBackwards: false,
    addToCur: true,
    curDeck: 1,
    newBury: true,
    newSpread: 0,
    dueCounts: true,
    curModel: null as number | null,
    collapseTime: 1200,
};

/** Default Anki deck configuration (``dconf``) — values copied
 *  from a fresh Anki 2.1 desktop export. */
export const DEFAULT_DCONF = {
    "1": {
        id: 1,
        name: "Default",
        replayq: true,
        lapse: {
            leechFails: 8,
            minInt: 1,
            delays: [10],
            leechAction: 0,
            mult: 0,
        },
        rev: {
            perDay: 200,
            fuzz: 0.05,
            ivlFct: 1,
            maxIvl: 36500,
            ease4: 1.3,
            bury: false,
            minSpace: 1,
        },
        timer: 0,
        maxTaken: 60,
        usn: 0,
        new: {
            perDay: 20,
            delays: [1, 10],
            separate: true,
            ints: [1, 4, 7],
            initialFactor: 2500,
            bury: false,
            order: 1,
        },
        mod: 0,
        autoplay: true,
    },
};

/**
 * Basic (front/back) model — 1 card per note.
 * ``mid`` is the model id; we pin it to a stable constant so
 * re-exports from the same project produce comparable .apkg
 * files for diffing.
 */
export const BASIC_MODEL_ID = 1607392319000;
/** Cloze model — N cards per note (one per ``{{c1::...}}``,
 *  ``{{c2::...}}`` etc.). */
export const CLOZE_MODEL_ID = 1607392319001;

export const BASIC_MODEL = {
    id: BASIC_MODEL_ID,
    name: "Basic",
    type: 0, // 0 = standard, 1 = cloze
    mod: 0,
    usn: 0,
    sortf: 0,
    did: 1,
    tmpls: [
        {
            name: "Card 1",
            ord: 0,
            qfmt: "{{Front}}",
            afmt: '{{FrontSide}}\n\n<hr id="answer">\n\n{{Back}}',
            bqfmt: "",
            bafmt: "",
            did: null,
            bfont: "",
            bsize: 0,
        },
    ],
    flds: [
        {
            name: "Front",
            ord: 0,
            sticky: false,
            rtl: false,
            font: "Arial",
            size: 20,
            description: "",
        },
        {
            name: "Back",
            ord: 1,
            sticky: false,
            rtl: false,
            font: "Arial",
            size: 20,
            description: "",
        },
    ],
    css: ".card {\n font-family: arial;\n font-size: 20px;\n text-align: center;\n color: black;\n background-color: white;\n}\n",
    latexPre: "",
    latexPost: "",
    latexsvg: false,
    req: [[0, "any", [0]]],
};

export const CLOZE_MODEL = {
    id: CLOZE_MODEL_ID,
    name: "Cloze",
    type: 1,
    mod: 0,
    usn: 0,
    sortf: 0,
    did: 1,
    tmpls: [
        {
            name: "Cloze",
            ord: 0,
            qfmt: "{{cloze:Text}}",
            afmt: "{{cloze:Text}}<br>\n{{Extra}}",
            bqfmt: "",
            bafmt: "",
            did: null,
            bfont: "",
            bsize: 0,
        },
    ],
    flds: [
        {
            name: "Text",
            ord: 0,
            sticky: false,
            rtl: false,
            font: "Arial",
            size: 20,
            description: "",
        },
        {
            name: "Extra",
            ord: 1,
            sticky: false,
            rtl: false,
            font: "Arial",
            size: 20,
            description: "",
        },
    ],
    css: ".card {\n font-family: arial;\n font-size: 20px;\n text-align: center;\n color: black;\n background-color: white;\n}\n.cloze {\n font-weight: bold;\n color: blue;\n}\n",
    latexPre: "",
    latexPost: "",
    latexsvg: false,
    req: [[0, "any", [0]]],
};
