/**
 * Markdown renderer for backup diffs (v1.12.0 / Phase 25E).
 *
 * Builds a human-readable report from the diff produced by
 * ``backup-diff``. Format:
 *
 *   - Top header with dates, versions, total record counts +
 *     delta one-liner.
 *   - Summary table (tables with zero deltas OMITTED).
 *   - Per-table sections (zero-delta tables OMITTED): added,
 *     removed, changed (with field-level old → new for each
 *     changed row).
 *   - High-volume tables (``session_messages``, etc.) render a
 *     count summary instead of one-line previews per record.
 *   - Footer watermark with the app version.
 *
 * The same renderer powers both the standalone "Export as
 * Markdown" button in BackupCompare and (potentially) any
 * future automation that wants a textual report. No external
 * deps, no I/O.
 */

import type {BackupDiff, TableDiff} from "./backup-diff";

export interface RenderMarkdownOptions {
    labelA: string;
    labelB: string;
    /** Override the "today" stamp at the top of the report. */
    now?: string;
}

/**
 * Render a human-readable Markdown report for a backup diff:
 * a header with dates/versions/totals, a summary table, and
 * per-table added/removed/changed sections (zero-delta tables
 * omitted, high-volume tables summarised by count).
 */
export function renderDiffMarkdown(
    diff: BackupDiff,
    opts: RenderMarkdownOptions,
): string {
    const lines: string[] = [];
    const dateA = isoDate(diff.backup_a.created_at);
    const dateB = isoDate(diff.backup_b.created_at);
    const now = opts.now ?? isoDate(new Date().toISOString());

    lines.push("# Backup Comparison Report");
    lines.push("");
    lines.push(`**Date:** ${now}`);
    lines.push(
        `**${opts.labelA}:** ${dateA}, ${diff.backup_a.app_version ?? "unknown"}, ${diff.backup_a.total_records} records`,
    );
    lines.push(
        `**${opts.labelB}:** ${dateB}, ${diff.backup_b.app_version ?? "unknown"}, ${diff.backup_b.total_records} records`,
    );
    lines.push(
        `**Delta:** +${diff.totals.added} added, -${diff.totals.removed} removed, ${diff.totals.changed} changed, ${diff.totals.unchanged} unchanged`,
    );
    lines.push("");
    lines.push("---");
    lines.push("");

    // Summary table — only tables with a non-zero delta.
    const changedTables = diff.tables.filter(hasDelta);
    lines.push("## Summary");
    lines.push("");
    if (changedTables.length === 0) {
        lines.push("_No differences between the two backups._");
    } else {
        lines.push("| Table | Added | Removed | Changed | Unchanged |");
        lines.push("|-------|-------|---------|---------|-----------|");
        for (const table of changedTables) {
            lines.push(
                `| ${table.table} | +${table.added.length} | -${table.removed.length} | ~${table.changed.length} | ${table.unchanged} |`,
            );
        }
    }
    lines.push("");
    lines.push("---");
    lines.push("");

    // Per-table sections — same omission rule (zero deltas
    // skipped) so the report stays short on small diffs.
    for (const table of changedTables) {
        lines.push(...renderTableSection(table));
        lines.push("");
        lines.push("---");
        lines.push("");
    }

    lines.push(`*Generated by Adaptive Learner v${__APP_VERSION__}*`);
    lines.push("");

    return lines.join("\n");
}

function hasDelta(table: TableDiff): boolean {
    return (
        table.added.length + table.removed.length + table.changed.length > 0
    );
}

function renderTableSection(table: TableDiff): string[] {
    const lines: string[] = [];
    const headerParts: string[] = [];
    if (table.added.length > 0) headerParts.push(`+${table.added.length} added`);
    if (table.removed.length > 0)
        headerParts.push(`-${table.removed.length} removed`);
    if (table.changed.length > 0)
        headerParts.push(`~${table.changed.length} changed`);
    lines.push(`## ${table.table} (${headerParts.join(", ")})`);
    lines.push("");

    // High-volume + append-only tables (session_messages,
    // imported_messages, step_evaluations) render a count
    // summary instead of one-line previews — listing 5000 rows
    // makes the report unreadable.
    if (table.high_volume) {
        if (table.added.length > 0) {
            lines.push(
                `${table.added.length} new records added (detail omitted for brevity).`,
            );
        }
        if (table.removed.length > 0) {
            lines.push(
                `${table.removed.length} records removed (detail omitted for brevity).`,
            );
        }
        if (table.changed.length > 0) {
            lines.push(
                `${table.changed.length} records changed (detail omitted for brevity).`,
            );
        }
        return lines;
    }

    if (table.added.length > 0) {
        lines.push("### Added");
        for (const rec of table.added) {
            lines.push(`- ${rec.preview}`);
        }
        lines.push("");
    }
    if (table.removed.length > 0) {
        lines.push("### Removed");
        for (const rec of table.removed) {
            lines.push(`- ${rec.preview}`);
        }
        lines.push("");
    }
    if (table.changed.length > 0) {
        lines.push("### Changed");
        for (const rec of table.changed) {
            lines.push(`- **${rec.preview}**:`);
            for (const field of rec.fields) {
                lines.push(
                    `  - ${field.field}: ${formatValueShort(field.old_value)} → ${formatValueShort(field.new_value)}`,
                );
            }
        }
        lines.push("");
    }

    return lines;
}

function formatValueShort(value: unknown): string {
    if (value === null) return "null";
    if (value === undefined) return "(unset)";
    if (typeof value === "string") {
        // Quote strings, escape pipes (Markdown table safety) +
        // truncate long content so a single huge field doesn't
        // dominate the section.
        const escaped = value.replace(/\|/g, "\\|");
        const max = 80;
        return escaped.length > max
            ? `"${escaped.slice(0, max)}…"`
            : `"${escaped}"`;
    }
    if (typeof value === "number" || typeof value === "boolean") {
        return String(value);
    }
    try {
        const json = JSON.stringify(value);
        if (json.length > 80) return json.slice(0, 80) + "…";
        return json;
    } catch {
        return String(value);
    }
}

function isoDate(value: string): string {
    const match = value.match(/^(\d{4}-\d{2}-\d{2})/);
    return match ? match[1] : value;
}

export const __test__ = {hasDelta, formatValueShort, renderTableSection, isoDate};
