import {clsx, type ClassValue} from "clsx";
import {twMerge} from "tailwind-merge";

/**
 * Merge class names with Tailwind-aware conflict resolution.
 *
 * Standard shadcn/ui helper: ``clsx`` flattens conditional class inputs,
 * ``tailwind-merge`` then de-duplicates conflicting Tailwind utilities so
 * the last one wins (e.g. ``cn("p-2", "p-4")`` -> ``"p-4"``). Every
 * shadcn/ui component generated by ``npx shadcn@latest add`` imports this
 * from ``@/lib/utils``.
 */
export function cn(...inputs: ClassValue[]): string {
  return twMerge(clsx(inputs));
}
