/**
 * First-paint strings for every UI language (#2796, #3378).
 *
 * The real language catalog is a lazily loaded chunk, so the shell paints
 * from this inline subset first, and keeps using it when the chunk cannot
 * load. The subset is GENERATED by ``make sync-i18n`` from
 * ``backend/config/i18n/*.yaml``: every key listed in ``shell-keys.json``, for
 * every catalog. It used to be a hand copy that covered 5 of 11 languages and
 * had drifted from the YAML (misspelled labels, English blocks).
 *
 * A key the shell renders before the chunk loads belongs in
 * ``shell-keys.json``; ``first-paint-coverage.test.ts`` fails when one is
 * missing, and ``fallbacks.test.ts`` fails when the generated file is stale.
 */

import shellCatalogs from "../data/i18n/first-paint/catalogs.json";

/** A nested catalog: values are strings or deeper groups (#2796 - the app's
 *  keys are not limited to two levels, e.g. ``update.banner.message``). */
type CatalogNode = string | {[key: string]: CatalogNode};
type Catalog = Record<string, CatalogNode>;

/** First-paint catalog per UI language code (all shipped catalogs). */
export const FALLBACK_CATALOGS: Record<string, Catalog> = shellCatalogs as Record<string, Catalog>;
